server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.88.128:8848 #配置Nacos地址
        server-addr: 192.168.88.128:80 #配置Nacos集群的VIP地址

management:
  endpoints:
    web:
      exposure:
        include: '*'