server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 负载均衡配置
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2 # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 负载均衡配置
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的进行路由
            - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai] # request made after Jan 20, 2020-03-12 Mountain Time (Shanghai)
            - Before=2021-03-12T15:44:15.064+08:00[Asia/Shanghai]
            - Between=2020-03-12T15:44:15.064+08:00[Asia/Shanghai], 2021-03-12T15:44:15.064+08:00[Asia/Shanghai]
            - Cookie=token, 1001 # have a cookie named 'token' whose value matches the '1001' regular expression
            - Header=X-Request-Id, \d+ # the request has a header named X-Request-Id whose value matches the \d+ regular expression
            - Host=**.jxgyl.com # the request has a Host header with a value of 'www.jxgyl.com' or 'devops.jxgyl.com'
            - Method=GET,POST # the request method was a GET or a POST
            - Query=red, gree. # the request contained a red query parameter whose value matched the gree. regexp, so green and greet would match


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka