server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.88.128:8848 #配置Nacos地址
        server-addr: 192.168.88.128:80 #配置Nacos集群的VIP地址

#消费者将去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider